<div x-data x-on:open-backup-schedule.window="$wire.open($event.detail.clientCode, $event.detail.connectionId)" x-on:backup-schedule-saved.window="Toast.fire({ icon: 'success', title: $event.detail.message })">
    <x-common.form-modal id="backup-schedule-modal" :title="__('Programación del respaldo')" :description="__('Configura la frecuencia y retención de esta conexión de respaldo.')" size="2xl">
        <form wire:submit="save" autocomplete="off" class="space-y-5">
            <label class="flex items-center gap-2 text-sm font-medium text-gray-700 dark:text-gray-300"><input wire:model.live="useCustomSchedule" type="checkbox" class="rounded border-gray-300 text-brand-500 focus:ring-brand-500" />{{ __('Usar configuración personalizada') }}</label>
            @if($useCustomSchedule)
                <div class="grid grid-cols-1 gap-4 sm:grid-cols-3">
                    <div><label for="schedule-frequency" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Frecuencia') }}</label><select id="schedule-frequency" wire:model="frequency" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 focus:ring-1 focus:ring-brand-500/30 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"><option value="hourly">{{ __('Cada hora') }}</option><option value="every_six_hours">{{ __('Cada 6 horas') }}</option><option value="every_twelve_hours">{{ __('Cada 12 horas') }}</option><option value="daily">{{ __('Una vez al día') }}</option><option value="every_two_days">{{ __('Día por medio') }}</option><option value="weekly">{{ __('Una vez por semana') }}</option></select>@error('frequency')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div>
                    <div><label for="schedule-months" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Recientes (meses)') }}</label><input id="schedule-months" wire:model="dailyRetentionMonths" type="number" min="1" max="12" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 focus:ring-1 focus:ring-brand-500/30 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90" />@error('dailyRetentionMonths')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div>
                    <div><label for="schedule-years" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Mensuales (años)') }}</label><input id="schedule-years" wire:model="monthlyRetentionYears" type="number" min="1" max="10" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 focus:ring-1 focus:ring-brand-500/30 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90" />@error('monthlyRetentionYears')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div>
                </div>
            @else
                <p class="rounded-lg bg-gray-50 p-3 text-sm text-gray-500 dark:bg-gray-900 dark:text-gray-400">{{ __('Esta conexión utilizará la configuración general de respaldos.') }}</p>
            @endif
            <x-common.form-actions><button type="button" x-on:click="$tsui.close.modal('backup-schedule-modal')" wire:click="close" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-300 dark:hover:bg-white/[0.03]">{{ __('Cancelar') }}</button><button type="submit" wire:loading.attr="disabled" class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white hover:bg-brand-600 disabled:cursor-not-allowed disabled:opacity-50"><span wire:loading.remove wire:target="save">{{ __('Guardar cambios') }}</span><span wire:loading wire:target="save">{{ __('Guardando...') }}</span></button></x-common.form-actions>
        </form>
    </x-common.form-modal>
</div>
