<div x-data x-on:open-backup-connection-create.window="$wire.openCreate($event.detail.clientCode)" x-on:open-backup-connection-edit.window="$wire.openEdit($event.detail.clientCode, $event.detail.connectionId)" x-on:backup-connection-tested.window="Toast.fire({ icon: 'success', title: $event.detail.message })">
    <x-common.form-modal id="backup-connection-modal" :title="$connectionId === null ? __('Nueva configuración de respaldo') : __('Configuración de respaldo')" :description="__('Configura el acceso SSH y la base de datos que se respaldará.')" size="3xl">
            <form wire:submit="save" autocomplete="off" x-init="$nextTick(() => $el.querySelectorAll('input:not([type=checkbox]):not([data-fixed-value])').forEach(input => { input.readOnly = true; input.addEventListener('focus', () => input.readOnly = false, { once: true }); }))" class="space-y-5">
            <div><label for="backup-database-type" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Tipo de base de datos') }}</label><select id="backup-database-type" wire:model="databaseType" class="h-10 w-full rounded-lg border border-gray-300 bg-white px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">@foreach($databaseTypes as $type)<option value="{{ $type['key'] }}">{{ $type['name'] }}</option>@endforeach</select>@error('databaseType')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div>

            <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div><label for="backup-connection-name" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Nombre') }}</label><input id="backup-connection-name" wire:model="name" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('name')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div>
                <div><label for="backup-connection-project" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Proyecto') }}</label><select id="backup-connection-project" wire:model="projectId" class="h-10 w-full rounded-lg border border-gray-300 bg-white px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"><option value="">{{ __('Todos los proyectos') }}</option>@foreach($projects as $project)<option value="{{ $project['id'] }}">{{ $project['name'] }}</option>@endforeach</select>@error('projectId')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div>
            </div>

            <div class="rounded-lg border border-gray-200 p-4 dark:border-gray-800"><h3 class="text-sm font-semibold text-gray-800 dark:text-white/90">{{ __('Acceso SSH') }}</h3><div class="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-3"><div class="sm:col-span-2"><label for="backup-ssh-host" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Servidor SSH') }}</label><input id="backup-ssh-host" wire:model="sshHost" type="text" autocomplete="off" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('sshHost')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div><div><label for="backup-ssh-port" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Puerto') }}</label><input id="backup-ssh-port" wire:model="sshPort" type="number" min="1" max="65535" autocomplete="off" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('sshPort')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div><div><label for="backup-ssh-user" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Usuario SSH') }}</label><input id="backup-ssh-user" name="ssh_login_value" wire:model="sshUser" type="text" autocomplete="new-password" readonly x-on:focus="$el.removeAttribute('readonly')" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('sshUser')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div></div></div>

            <div class="rounded-lg border border-gray-200 p-4 dark:border-gray-800"><h3 class="text-sm font-semibold text-gray-800 dark:text-white/90">{{ __('Base de datos') }}</h3><div class="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2"><div><label for="backup-postgres-host" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Servidor') }}</label><input id="backup-postgres-host" wire:model="postgresHost" type="text" readonly data-fixed-value="true" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('postgresHost')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div><div><label for="backup-postgres-port" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Puerto') }}</label><input id="backup-postgres-port" wire:model="postgresPort" type="number" min="1" max="65535" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('postgresPort')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div><div><label for="backup-postgres-database" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Base de datos') }}</label><input id="backup-postgres-database" wire:model="postgresDatabase" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('postgresDatabase')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div><div><label for="backup-postgres-user" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Usuario') }}</label><input id="backup-postgres-user" wire:model="postgresUser" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('postgresUser')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div><div><label for="backup-postgres-password" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Contraseña') }}</label><input id="backup-postgres-password" wire:model="postgresPassword" type="password" autocomplete="new-password" readonly x-on:focus="$el.removeAttribute('readonly')" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('postgresPassword')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div></div></div>

            @if($databaseType === 'mysql')
                <div class="rounded-lg border border-gray-200 p-4 dark:border-gray-800">
                    <h3 class="text-sm font-semibold text-gray-800 dark:text-white/90">{{ __('Parámetros de conexión MySQL') }}</h3>
                    <div class="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2">
                        <div><label for="backup-mysql-host" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Servidor') }}</label><input id="backup-mysql-host" wire:model="mysqlHost" type="text" readonly data-fixed-value="true" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('mysqlHost')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div>
                        <div><label for="backup-mysql-port" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Puerto') }}</label><input id="backup-mysql-port" wire:model="mysqlPort" type="number" min="1" max="65535" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('mysqlPort')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div>
                        <div><label for="backup-mysql-database" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Base de datos') }}</label><input id="backup-mysql-database" wire:model="mysqlDatabase" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('mysqlDatabase')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div>
                        <div><label for="backup-mysql-user" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Usuario') }}</label><input id="backup-mysql-user" wire:model="mysqlUser" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('mysqlUser')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div>
                        <div><label for="backup-mysql-password" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Contraseña') }}</label><input id="backup-mysql-password" name="mysql_secret_value" wire:model="mysqlPassword" type="password" autocomplete="new-password" readonly x-on:focus="$el.removeAttribute('readonly')" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('mysqlPassword')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div>
                    </div>
                </div>
            @endif

            <label class="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300"><input wire:model="isActive" type="checkbox" class="rounded border-gray-300 text-brand-500 focus:ring-brand-500" />{{ __('Configuración activa') }}</label>
            @error('connectionTest')<small class="block text-xs text-red-500">{{ $message }}</small>@enderror
            <x-common.form-actions><button type="button" wire:click="testConnection" wire:loading.attr="disabled" wire:target="testConnection" class="rounded-lg border border-brand-200 px-4 py-2.5 text-sm font-medium text-brand-600 hover:bg-brand-50 disabled:cursor-not-allowed disabled:opacity-50 dark:border-brand-500/30 dark:text-brand-400 dark:hover:bg-brand-500/10"><span wire:loading.remove wire:target="testConnection">{{ __('Comprobar conexión') }}</span><span wire:loading wire:target="testConnection">{{ __('Comprobando...') }}</span></button><button type="button" x-on:click="$tsui.close.modal('backup-connection-modal')" wire:click="close" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-300 dark:hover:bg-white/[0.03]">{{ __('Cancelar') }}</button><button type="submit" wire:loading.attr="disabled" class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white hover:bg-brand-600 disabled:cursor-not-allowed disabled:opacity-50"><span wire:loading.remove wire:target="save">{{ $connectionId === null ? __('Guardar configuración') : __('Actualizar configuración') }}</span><span wire:loading wire:target="save">{{ __('Guardando...') }}</span></button></x-common.form-actions>
            </form>
    </x-common.form-modal>
</div>
