<div x-data="{ modalOpen: false, modalReady: false }"
    x-on:open-client-create.window="modalOpen = true; modalReady = false; $wire.openCreate().then(() => modalReady = true)"
    x-on:client-saved.window="modalOpen = false; Toast.fire({ icon: 'success', title: $event.detail.message })">
    <div x-cloak x-show="modalOpen" x-transition.opacity class="fixed inset-0 z-[100000] flex items-start justify-center overflow-y-auto p-3 sm:items-center sm:p-5">
        <div x-transition.opacity class="fixed inset-0 bg-gray-950/70" x-on:click="modalOpen = false" wire:click="close"></div>
        <div x-transition:enter="transition ease-out duration-200" x-transition:enter-start="scale-95 opacity-0" x-transition:enter-end="scale-100 opacity-100" x-transition:leave="transition ease-in duration-150" x-transition:leave-start="scale-100 opacity-100" x-transition:leave-end="scale-95 opacity-0" class="relative z-10 my-auto flex max-h-[calc(100vh-1.5rem)] w-full max-w-[850px] flex-col overflow-hidden rounded-2xl border border-gray-200 bg-white p-4 shadow-xl dark:border-gray-800 dark:bg-gray-900 sm:rounded-3xl sm:p-5 lg:p-8">
            <x-common.modal-close x-on:click="modalOpen = false" wire:click="close" />

            <div class="mb-6 shrink-0 pr-8"><h2 class="text-2xl font-semibold text-gray-800 dark:text-white/90">{{ $clientId === null ? __('Nuevo cliente') : __('Editar cliente') }}</h2><p class="mt-2 text-sm text-gray-500 dark:text-gray-400">{{ __('Registra la información general, el contacto y la dirección principal.') }}</p></div>

            <div class="custom-scrollbar min-h-0 flex-1 overflow-y-auto pr-2">
                <div x-cloak x-show="!modalReady" class="flex min-h-[520px] items-center justify-center" role="status" aria-live="polite">
                    <div class="flex items-center gap-3 text-sm text-gray-500 dark:text-gray-400">
                        <svg class="h-5 w-5 animate-spin text-brand-500" viewBox="0 0 24 24" fill="none" aria-hidden="true">
                            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 0 1 8-8V1C6.925 1 2 5.925 2 12h2Zm8 8a8 8 0 0 1-8-8H1c0 6.075 4.925 11 11 11v-3Z"></path>
                        </svg>
                        <span>{{ __('Cargando información...') }}</span>
                    </div>
                </div>

                <div x-cloak x-show="modalReady">
                <form wire:submit="save" class="space-y-6" enctype="multipart/form-data">
                    <fieldset wire:loading.attr="disabled" wire:target="lookupPerson, lookupCompany" class="contents">
                    <div class="grid grid-cols-12 gap-5">
                        <div class="col-span-12 sm:col-span-6"><label for="client-type" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Tipo') }}</label><select id="client-type" wire:model.live="type" class="h-10 w-full rounded-lg border border-gray-300 bg-white px-3 text-sm text-gray-800 dark:border-gray-700 dark:bg-gray-800 dark:text-white/90"><option value="company" class="bg-white text-gray-800 dark:bg-gray-800 dark:text-white">{{ __('Empresa') }}</option><option value="person" class="bg-white text-gray-800 dark:bg-gray-800 dark:text-white">{{ __('Persona') }}</option></select>@error('type')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div>
                        @if($type === 'person')
                            <div class="col-span-12 sm:col-span-6"><label for="client-tax-id" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Cédula') }}</label><div class="flex items-center gap-2"><input id="client-tax-id" wire:model="taxId" type="text" wire:loading.attr="disabled" wire:target="lookupPerson" class="h-10 min-w-0 flex-1 rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90 disabled:cursor-not-allowed disabled:bg-gray-100 dark:disabled:bg-white/[0.03]"><button type="button" wire:click="lookupPerson" wire:loading.attr="disabled" wire:target="lookupPerson" class="inline-flex h-10 shrink-0 items-center justify-center rounded-lg bg-brand-500 px-3 text-sm font-medium text-white hover:bg-brand-600 disabled:cursor-not-allowed disabled:opacity-50"><span wire:loading.remove wire:target="lookupPerson">{{ __('Consultar') }}</span><span wire:loading wire:target="lookupPerson" aria-label="{{ __('Consultando...') }}"><svg class="h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 0 1 8-8V1C6.925 1 2 5.925 2 12h2Zm8 8a8 8 0 0 1-8-8H1c0 6.075 4.925 11 11 11v-3Z"></path></svg></span></button></div>@error('taxId')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror @error('lookup')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div>
                        @else
                            <div class="col-span-12 sm:col-span-6"><label for="client-tax-id" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Identificación fiscal') }}</label><div class="flex items-center gap-2"><input id="client-tax-id" wire:model="taxId" type="text" wire:loading.attr="disabled" wire:target="lookupCompany" class="h-10 min-w-0 flex-1 rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90 disabled:cursor-not-allowed disabled:bg-gray-100 dark:disabled:bg-white/[0.03]"><button type="button" wire:click="lookupCompany" wire:loading.attr="disabled" wire:target="lookupCompany" class="inline-flex h-10 shrink-0 items-center justify-center rounded-lg bg-brand-500 px-3 text-sm font-medium text-white hover:bg-brand-600 disabled:cursor-not-allowed disabled:opacity-50"><span wire:loading.remove wire:target="lookupCompany">{{ __('Consultar') }}</span><span wire:loading wire:target="lookupCompany" aria-label="{{ __('Consultando...') }}"><svg class="h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 0 1 8-8V1C6.925 1 2 5.925 2 12h2Zm8 8a8 8 0 0 1-8-8H1c0 6.075 4.925 11 11 11v-3Z"></path></svg></span></button></div>@error('taxId')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror @error('lookup')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div>
                        @endif
                        <div class="col-span-12 sm:col-span-6 sm:col-start-1"><label for="client-name" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Nombre') }}</label><input id="client-name" wire:model="name" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:text-white/90">@error('name')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div>
                        <div class="col-span-12 sm:col-span-6"><label for="client-email" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Correo electrónico') }}</label><input id="client-email" wire:model="email" type="email" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:text-white/90">@error('email')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div>
                        <div class="col-span-12 sm:col-span-6"><label for="client-phone" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Teléfono') }}</label><input id="client-phone" wire:model="phone" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:text-white/90">@error('phone')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div>
                        <div class="col-span-12 sm:col-span-6"><label for="client-website" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Sitio web') }}</label><input id="client-website" wire:model="website" type="url" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:text-white/90">@error('website')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div>
                        <div class="col-span-12 sm:col-span-6"><label for="client-image" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Imagen o logo') }}</label><input id="client-image" wire:model="image" type="file" accept="image/jpeg,image/png,image/webp" class="block w-full text-sm text-gray-500">@error('image')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div>
                    </div>
                    @if($clientId !== null)
                    <div><label for="client-details" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Detalles') }}</label><textarea id="client-details" wire:model="details" rows="3" class="w-full rounded-lg border border-gray-300 bg-transparent px-3 py-2 text-sm dark:border-gray-700 dark:text-white/90"></textarea>@error('details')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div>
                    <div class="border-t border-gray-200 pt-5 dark:border-gray-800"><h3 class="mb-4 text-lg font-medium text-gray-800 dark:text-white/90">{{ __('Contacto principal') }}</h3><div class="grid grid-cols-1 gap-5 sm:grid-cols-2"><div><label for="contact-name" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Nombre') }}</label><input id="contact-name" wire:model="contactName" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:text-white/90"></div><div><label for="contact-position" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Cargo') }}</label><input id="contact-position" wire:model="contactPosition" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:text-white/90"></div><div><label for="contact-email" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Correo del contacto') }}</label><input id="contact-email" wire:model="contactEmail" type="email" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:text-white/90"></div><div><label for="contact-phone" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Teléfono del contacto') }}</label><input id="contact-phone" wire:model="contactPhone" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:text-white/90"></div></div></div>
                    <div class="border-t border-gray-200 pt-5 dark:border-gray-800"><h3 class="mb-4 text-lg font-medium text-gray-800 dark:text-white/90">{{ __('Dirección principal') }}</h3><div class="grid grid-cols-1 gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label for="address-line" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Dirección') }}</label><input id="address-line" wire:model="addressLine" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:text-white/90"></div><div><label for="address-city" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Ciudad') }}</label><input id="address-city" wire:model="city" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:text-white/90"></div><div><label for="address-state" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Provincia o estado') }}</label><input id="address-state" wire:model="state" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:text-white/90"></div><div><label for="address-country" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('País') }}</label><input id="address-country" wire:model="country" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:text-white/90"></div><div><label for="address-postal-code" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Código postal') }}</label><input id="address-postal-code" wire:model="postalCode" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:text-white/90"></div></div></div>
                    @endif
                    <div class="flex justify-end gap-3 pt-3"><button type="button" x-on:click="modalOpen = false" wire:click="close" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-medium text-gray-700 dark:border-gray-700 dark:text-gray-300">{{ __('Cancelar') }}</button><button type="submit" wire:loading.attr="disabled" class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white hover:bg-brand-600 disabled:opacity-50"><span wire:loading.remove wire:target="save">{{ __('Guardar cliente') }}</span><span wire:loading wire:target="save">{{ __('Guardando...') }}</span></button></div>
                    </fieldset>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
