<div x-data="{ modalReady: false }" x-on:open-domain-create.window="modalReady = false; $wire.openCreate($event.detail.clientCode).then(() => modalReady = true)" x-on:open-domain-edit.window="modalReady = false; $wire.openEdit($event.detail.clientCode, $event.detail.domainId).then(() => modalReady = true)" x-on:domain-saved.window="Toast.fire({ icon: 'success', title: $event.detail.message })">
    <x-common.form-modal id="domain-modal" :title="$domainId === null ? __('Nuevo dominio') : __('Editar dominio')" :description="__('Registra la información de hospedaje, pago y renovación del dominio.')" size="2xl">
        <div x-cloak x-show="!modalReady" class="flex min-h-[300px] items-center justify-center" role="status"><span class="text-sm text-gray-500 dark:text-gray-400">{{ __('Cargando información...') }}</span></div>
        <div x-cloak x-show="modalReady"><form wire:submit="save" autocomplete="off" class="space-y-5">
            @if($this->isMigrationPending())
                <div role="alert" class="flex items-center gap-1 rounded-md border border-orange-200/50 bg-orange-50/30 px-1 py-2 text-sm font-normal text-orange-700/70 dark:border-orange-500/30 dark:bg-orange-500/15 dark:text-orange-300"><i data-lucide="triangle-alert" class="h-4 w-4 shrink-0 text-orange-400 dark:text-orange-300" aria-hidden="true"></i><span>{{ __('Pendiente de migración a DonDominio') }}</span></div>
            @endif
            <div class="grid grid-cols-1 gap-5 sm:grid-cols-2"><div><x-input id="domain-name" wire:model="name" type="text" :label="__('Dominio')" />@error('name')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div><div><x-input id="domain-hosting-provider" wire:model="hostingProvider" type="text" :label="__('Proveedor de hospedaje')" />@error('hostingProvider')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div><div><x-input id="domain-annual-cost" wire:model="annualCost" type="number" min="0" step="0.01" :label="__('Pago anual')" />@error('annualCost')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div><div><x-select.native id="domain-currency" wire:model="currency" :label="__('Moneda')"><option value="CRC">{{ __('Colones') }}</option><option value="USD">{{ __('Dólares') }}</option><option value="EUR">{{ __('Euros') }}</option></x-select.native>@error('currency')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div><div><label for="domain-expires-at" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Fecha de vencimiento') }}</label><input id="domain-expires-at" wire:model="expiresAt" type="text" data-datepicker class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" placeholder="dd/mm/aaaa" />@error('expiresAt')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div><div><x-input id="domain-renewal-period" wire:model="renewalPeriodYears" type="number" min="1" max="10" :label="__('Renovación (años)')" />@error('renewalPeriodYears')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div></div>
            <div><x-textarea id="domain-notes" wire:model="notes" rows="3" :label="__('Notas')" />@error('notes')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div>
            <x-common.form-actions><button type="button" x-on:click="$tsui.close.modal('domain-modal')" wire:click="close" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-300 dark:hover:bg-white/[0.03]">{{ __('Cancelar') }}</button><button type="submit" wire:loading.attr="disabled" class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white hover:bg-brand-600 disabled:cursor-not-allowed disabled:opacity-50"><span wire:loading.remove wire:target="save">{{ __('Guardar dominio') }}</span><span wire:loading wire:target="save">{{ __('Guardando...') }}</span></button></x-common.form-actions>
        </form></div>
    </x-common.form-modal>
</div>
