<div x-data="{ modalReady: false }" x-on:open-project-create.window="modalReady = false; $wire.openCreate($event.detail.clientCode).then(() => modalReady = true)" x-on:open-project-edit.window="modalReady = false; $wire.openEdit($event.detail.clientCode, $event.detail.projectId).then(() => modalReady = true)" x-on:project-saved.window="Toast.fire({ icon: 'success', title: $event.detail.message })">
    <x-modal id="project-modal" wire="isOpen" z-index="z-[70]" size="2xl" scrollable center :title="$projectId === null ? __('Nuevo proyecto') : __('Editar proyecto')" x-on:close="$wire.close()">
        <div x-cloak x-show="!modalReady" class="flex min-h-[300px] items-center justify-center" role="status" aria-live="polite"><div class="flex items-center gap-3 text-sm text-gray-500 dark:text-gray-400"><svg class="h-5 w-5 animate-spin text-brand-500" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 0 1 8-8V1C6.925 1 2 5.925 2 12h2Zm8 8a8 8 0 0 1-8-8H1c0 6.075 4.925 11 11 11v-3Z"></path></svg><span>{{ __('Cargando información...') }}</span></div></div>
        <div x-cloak x-show="modalReady"><div class="mb-6 pr-8"><p class="mt-2 text-sm text-gray-500 dark:text-gray-400">{{ __('Completa la información del proyecto.') }}</p></div><form wire:submit="save" autocomplete="off" class="space-y-5">
            <div><label for="project-name" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Nombre') }}</label><input id="project-name" wire:model="name" type="text" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('name')<small class="mt-1 block text-xs text-red-500">{{ $message }}</small>@enderror</div>
            <div><x-editor id="project-description" wire:model="description" :label="__('Descripción')" :toolbar="['style', 'bold', 'italic', 'underline', 'strikethrough', 'blockquote', 'unordered-list', 'ordered-list', 'undo', 'redo']" min-height="12rem" max-height="24rem" counters /></div>
            <div class="flex justify-end gap-3 pt-3"><button type="button" x-on:click="$tsui.close.modal('project-modal')" wire:click="close" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-300 dark:hover:bg-white/[0.03]">{{ __('Cancelar') }}</button><button type="submit" wire:loading.attr="disabled" class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white hover:bg-brand-600 disabled:cursor-not-allowed disabled:opacity-50"><span wire:loading.remove wire:target="save">{{ __('Guardar proyecto') }}</span><span wire:loading wire:target="save">{{ __('Guardando...') }}</span></button></div>
        </form></div>
    </x-modal>
</div>
