<div x-data="{ modalReady: false, passwordVisible: false }" x-on:open-project-credential-create.window="modalReady = false; passwordVisible = false; $wire.openCreate($event.detail.clientCode, $event.detail.projectId).then(() => modalReady = true)" x-on:open-project-credential-edit.window="modalReady = false; passwordVisible = false; $wire.openEdit($event.detail.clientCode, $event.detail.projectId, $event.detail.credentialId).then(() => modalReady = true)" x-on:project-credential-saved.window="Toast.fire({ icon: 'success', title: $event.detail.message })">
    <x-common.form-modal id="project-credential-modal" :title="$credentialId === null ? __('Nueva credencial') : __('Editar credencial')" :description="__('Guarda los datos de acceso para que el equipo pueda consultarlos.')" size="2xl">
        <div x-cloak x-show="!modalReady" class="flex min-h-[300px] items-center justify-center" role="status"><span class="text-sm text-gray-500 dark:text-gray-400">{{ __('Cargando información...') }}</span></div>
        <div x-cloak x-show="modalReady"><form wire:submit="save" autocomplete="off" class="space-y-5">
            <div class="grid grid-cols-1 gap-5 sm:grid-cols-2">
                <div><x-input id="credential-name" wire:model="name" type="text" :label="__('Nombre')" />@error('name')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div>
                <div><x-select.native id="credential-type" wire:model="type" :label="__('Tipo de acceso')"><option value="wordpress">{{ __('WordPress') }}</option><option value="hosting">{{ __('Hosting') }}</option><option value="ftp">{{ __('FTP') }}</option><option value="cpanel">{{ __('cPanel') }}</option><option value="other">{{ __('Otro') }}</option></x-select.native>@error('type')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div>
                <div class="sm:col-span-2"><x-input id="credential-login-url" wire:model="loginUrl" type="url" :label="__('Enlace de acceso')" placeholder="https://" />@error('loginUrl')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div>
                <div><x-input id="credential-username" wire:model="username" type="text" autocomplete="off" :label="__('Usuario')" />@error('username')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div>
                <div><label for="credential-password" class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{{ __('Contraseña') }}</label><input id="credential-password" wire:model="password" :type="passwordVisible ? 'text' : 'password'" autocomplete="new-password" placeholder="{{ $credentialId === null ? __('Contraseña') : __('Dejar vacía para conservarla') }}" class="h-10 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm text-gray-800 outline-none focus:border-brand-500 dark:border-gray-700 dark:text-white/90" />@error('password')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div>
            </div>
            <div><x-textarea id="credential-notes" wire:model="notes" rows="3" :label="__('Notas')" />@error('notes')<small class="text-xs text-red-500">{{ $message }}</small>@enderror</div>
            <x-common.form-actions><button type="button" x-on:click="$tsui.close.modal('project-credential-modal'); $wire.close()" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-300 dark:hover:bg-white/[0.03]">{{ __('Cancelar') }}</button><button type="submit" wire:loading.attr="disabled" class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white hover:bg-brand-600 disabled:cursor-not-allowed disabled:opacity-50"><span wire:loading.remove wire:target="save">{{ __('Guardar credencial') }}</span><span wire:loading wire:target="save">{{ __('Guardando...') }}</span></button></x-common.form-actions>
        </form></div>
    </x-common.form-modal>
</div>
